name: Rollback Prod

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'TAG: (format: vx.x.x)'
        required: true

env: 
  AWS_REGION: us-east-1
  APP_NAMESPACE: ${artifactId}
  APP_NAME: ${artifactId}
  AWS_PROD_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
  AWS_PROD_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
  AWS_PROD_ACCOUNT_ID: ${{ secrets.AWS_PROD_ACCOUNT_ID }}
  KUBE_CONFIG_DATA: ${{ secrets.AWS_PROD_EKS_KUBE_CONFIG }}


jobs:                                                  
  deploy-kubernetes-prod:
    name: Rollback Kubernetes PROD
    runs-on: [deployer-prod]
    timeout-minutes: 15
    steps:
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_PROD_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_PROD_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
        
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Checkout
        uses: actions/checkout@v2

##Prepare K8s files##

      - name: Replace image name
        env:
          RELEASE_IMAGE: ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_NAME }}:${{ github.event.inputs.tag }}
        run: sed -i 's|__IMAGE__|${{ env.RELEASE_IMAGE }}|g' kubernetes/*.yaml

      - name: Replace namespace
        run: sed -i 's|__NAMESPACE__|${{ env.APP_NAMESPACE }}|g' kubernetes/*.yaml

      - name: Replace app name
        run: sed -i 's|__APP-NAME__|${{ env.APP_NAME }}|g' kubernetes/*.yaml

      - name: Replace min replicas
        run: sed -i 's|__MIN_REPLICAS__|2|g' kubernetes/*.yaml

      - name: Replace max replicas
        run: sed -i 's|__MAX_REPLICAS__|10|g' kubernetes/*.yaml

      - name: Replace ingress annotation
        run: sed -i 's|__ENVIRONMENT__|prod|g' kubernetes/*.yaml

      - name: Replace dns
        run: sed -i 's|__DNS__|amaro.pro|g' kubernetes/*.yaml

##Deploy to EKS##

      - name: Create NS
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: apply -f kubernetes/*-namespace.yaml

      - name: Apply configmap to Kubernetes cluster
        uses: kodermax/kubectl-aws-eks@master
        with:                                                            
          args: apply -f kubernetes/*-configmap-prod.yaml

      - name: Apply deployment to Kubernetes cluster
        uses: kodermax/kubectl-aws-eks@master
        with:                                                            
          args: apply -f kubernetes/*-deployment.yaml

      - name: Apply service to Kubernetes cluster
        uses: kodermax/kubectl-aws-eks@master
        with:                                                            
          args: apply -f kubernetes/*-service.yaml

      - name: Apply ingress to Kubernetes cluster
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: apply -f kubernetes/*-ingress.yaml

      - name: Apply HPA to Kubernetes cluster
        uses: kodermax/kubectl-aws-eks@master
        with:
          args: apply -f kubernetes/*-hpa.yaml

      - name: Verify Kubernetes deployment
        id: rollout-status
        timeout-minutes: 10
        uses: kodermax/kubectl-aws-eks@master
        continue-on-error: true
        with:
          args: rollout status deploy ${{env.APP_NAME}}-deployment -n $APP_NAMESPACE